<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Mail\MailFormatHelper;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\user\Entity\User;

/**
 * Unpublish new nodes authored by anonymous users.
 * @param  EntityInterface $node
 */
function custom_publishing_node_presave(EntityInterface $node) {
  $account = \Drupal::currentUser();
  $user = User::load($account->id());
  $user_roles = $user->getRoles();

  $config = \Drupal::service('config.factory')->get('custom_publishing.settings');

  if (array_intersect($config->get('roles'), $user_roles) && in_array($node->bundle(), $config->get('types'))) {
    $node->setPublished(FALSE);
    \Drupal\Core\Messenger\MessengerInterface::addMessage(t($node->type->entity->label() .' has been submitted for approval.'));
  }
}

/**
 * Send email notification upon new nodes authored by anonymous users.
 * @param  EntityInterface $node
 */
function custom_publishing_node_insert(EntityInterface $node) {
  $config = \Drupal::service('config.factory')->get('custom_publishing.settings');
  $account = \Drupal::currentUser();
  if ($config->get('notify') && $account->isAnonymous()) {
    // Set the recipient address.
    $config = \Drupal::service('config.factory')->get('custom_publishing.settings');
    $site = \Drupal::service('config.factory')->get('system.site');
    $to = $config->get('notify_address') ? $config->get('notify_address') : $site->get('mail');
    // Parameters.
    $params = [];
    $params['node'] = $node;
    $lang = $node->langcode->value;
    // Send the email.
    $mailManager = \Drupal::service('plugin.manager.mail');
    $result = $mailManager->mail('custom_publishing', 'anonymous_node_insert', $to, $lang, $params, NULL, TRUE);
  }
}

/**
 * Implements hook_mail().
 */
function custom_publishing_mail($key, &$message, $params) {
  // Only hook_mail for anonymous users inserting nodes.
  if ($key === 'anonymous_node_insert') {
    $site = \Drupal::service('config.factory')->get('system.site');
    $config = \Drupal::service('config.factory')->get('custom_publishing.settings');
    // Grab the node.
    $node = $params['node'];
    // Set up the fields.
    $title = $node->getTitle();
    $link = \Drupal::request()->getSchemeAndHttpHost() . \Drupal::service('path.alias_manager')->getAliasByPath('/node/'. $node->id());
    $type = strtolower(node_get_type_label($node));
    $created = date('l, m/d/Y \a\t g:ia', $node->getCreatedTime()) . ' ' . date_default_timezone_get();
    $sitename = $site->get('name');
    // Token replacements.
    $tokens = array(
      '[[title]]' => $title,
      '[[link]]' => $link,
      '[[created]]' => $created,
      '[[type]]' => $type,
      '[[sitename]]' => $sitename,
    );
    // Assign the subject.
    if ($subject = $config->get('notify_subject')) {
      $subject = strtr($subject, $tokens);
      $message['subject'] = $subject;
    } else {
      $message['subject'] = 'New ' . $type . ' "' . $title . '" was submitted at ' . $sitename;
    }
    // Assign the body.
    if ($body = $config->get('notify_message')) {
      $body = strtr($body, $tokens);
      $message['body'][] = $body;
    } else {
      $message['body'][] = "Greetings,\n\n" . 'New ' . $type . ' "' . $title . '" was submitted anonymously at ' . $sitename . ' on ' . $created . ".\n\n" . $link;
    }
  }
}
