custom_publishing.settings:
  type: config_object
  label: 'Custom publishing settings'
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
    types:
      type: sequence
      label: 'Types'
      sequence:
        type: string
    notify:
      type: string
      label: 'Enable notification email'
    notify_address:
      type: string
      label: 'Notification email address'
    notify_subject:
      type: string
      label: 'Notification email subject'
    notify_message:
      type: string
      label: 'Notification email message body'
